exports.mappings =
	[
		["Thing", "Thing"],
		["CreativeWork", "Creative Work"],
		["Article", "Article"],
		["BlogPosting", "Blog Posting"],
		["NewsArticle", "News Article"],
		["ScholarlyArticle", "Scholarly Article"],
		["MedicalScholarlyArticle", "Medical Scholarly Article"],
		["Blog", "Blog"],
		["Book", "Book"],
		["Comment", "Comment"],
		["Diet", "Diet"],
		["ExercisePlan", "Exercise Plan"],
		["ItemList", "Item List"],
		["Map", "Map"],
		["MediaObject", "Media Object"],
		["AudioObject", "Audio Object"],
		["ImageObject", "Image Object"],
		["MusicVideoObject", "Music Video Object"],
		["VideoObject", "Video Object"],
		["Movie", "Movie"],
		["MusicPlaylist", "Music Playlist"],
		["MusicAlbum", "Music Album"],
		["MusicRecording", "Music Recording"],
		["Painting", "Painting"],
		["Photograph", "Photograph"],
		["Recipe", "Recipe"],
		["Review", "Review"],
		["Sculpture", "Sculpture"],
		["SoftwareApplication", "Software Application"],
		["MobileApplication", "Mobile Application"],
		["WebApplication", "Web Application"],
		["TVEpisode", "TV Episode"],
		["TVSeason", "TV Season"],
		["TVSeries", "TV Series"],
		["WebPage", "Web Page"],
		["AboutPage", "About Page"],
		["CheckoutPage", "Checkout Page"],
		["CollectionPage", "Collection Page"],
		["ImageGallery", "Image Gallery"],
		["VideoGallery", "Video Gallery"],
		["ContactPage", "Contact Page"],
		["ItemPage", "Item Page"],
		["MedicalWebPage", "Medical Web Page"],
		["ProfilePage", "Profile Page"],
		["SearchResultsPage", "Search Results Page"],
		["WebPageElement", "Web Page Element"],
		["SiteNavigationElement", "Site Navigation Element"],
		["Table", "Table"],
		["WPAdBlock", "WP Ad Block"],
		["WPFooter", "WP Footer"],
		["WPHeader", "WP Header"],
		["WPSideBar", "WP Side Bar"],
		["Event", "Event"],
		["BusinessEvent", "Business Event"],
		["ChildrensEvent", "Childrens Event"],
		["ComedyEvent", "Comedy Event"],
		["DanceEvent", "Dance Event"],
		["EducationEvent", "Education Event"],
		["Festival", "Festival"],
		["FoodEvent", "Food Event"],
		["LiteraryEvent", "Literary Event"],
		["MusicEvent", "Music Event"],
		["SaleEvent", "Sale Event"],
		["SocialEvent", "Social Event"],
		["SportsEvent", "Sports Event"],
		["TheaterEvent", "Theater Event"],
		["UserInteraction", "User Interaction"],
		["UserBlocks", "User Blocks"],
		["UserCheckins", "User Checkins"],
		["UserComments", "User Comments"],
		["UserDownloads", "User Downloads"],
		["UserLikes", "User Likes"],
		["UserPageVisits", "User Page Visits"],
		["UserPlays", "User Plays"],
		["UserPlusOnes", "User Plus Ones"],
		["UserTweets", "User Tweets"],
		["VisualArtsEvent", "Visual Arts Event"],
		["Intangible", "Intangible"],
		["Audience", "Audience"],
		["MedicalAudience", "Medical Audience"],
		["Enumeration", "Enumeration"],
		["BookFormatType", "Book Format Type"],
		["ItemAvailability", "Item Availability"],
		["OfferItemCondition", "Offer Item Condition"],
		["Specialty", "Specialty"],
		["MedicalSpecialty", "Medical Specialty"],
		["JobPosting", "Job Posting"],
		["Language", "Language"],
		["Offer", "Offer"],
		["AggregateOffer", "Aggregate Offer"],
		["Quantity", "Quantity"],
		["Distance", "Distance"],
		["Duration", "Duration"],
		["Energy", "Energy"],
		["Mass", "Mass"],
		["Rating", "Rating"],
		["AggregateRating", "Aggregate Rating"],
		["StructuredValue", "Structured Value"],
		["ContactPoint", "Contact Point"],
		["PostalAddress", "Postal Address"],
		["GeoCoordinates", "Geo Coordinates"],
		["GeoShape", "Geo Shape"],
		["NutritionInformation", "Nutrition Information"],
		["MedicalEntity", "Medical Entity"],
		["AnatomicalStructure", "Anatomical Structure"],
		["Bone", "Bone"],
		["BrainStructure", "Brain Structure"],
		["Joint", "Joint"],
		["Ligament", "Ligament"],
		["Muscle", "Muscle"],
		["Nerve", "Nerve"],
		["Vessel", "Vessel"],
		["Artery", "Artery"],
		["LymphaticVessel", "Lymphatic Vessel"],
		["Vein", "Vein"],
		["AnatomicalSystem", "Anatomical System"],
		["MedicalCause", "Medical Cause"],
		["MedicalCondition", "Medical Condition"],
		["InfectiousDisease", "Infectious Disease"],
		["MedicalContraindication", "Medical Contraindication"],
		["MedicalDevice", "Medical Device"],
		["MedicalGuideline", "Medical Guideline"],
		["MedicalGuidelineContraindication", "Medical Guideline Contraindication"],
		["MedicalGuidelineRecommendation", "Medical Guideline Recommendation"],
		["MedicalIndication", "Medical Indication"],
		["ApprovedIndication", "Approved Indication"],
		["PreventionIndication", "Prevention Indication"],
		["TreatmentIndication", "Treatment Indication"],
		["MedicalIntangible", "Medical Intangible"],
		["DDxElement", "D Dx Element"],
		["DoseSchedule", "Dose Schedule"],
		["MaximumDoseSchedule", "Maximum Dose Schedule"],
		["RecommendedDoseSchedule", "Recommended Dose Schedule"],
		["ReportedDoseSchedule", "Reported Dose Schedule"],
		["DrugCost", "Drug Cost"],
		["DrugLegalStatus", "Drug Legal Status"],
		["DrugStrength", "Drug Strength"],
		["MedicalCode", "Medical Code"],
		["MedicalConditionStage", "Medical Condition Stage"],
		["MedicalEnumeration", "Medical Enumeration"],
		["DrugCostCategory", "Drug Cost Category"],
		["DrugPregnancyCategory", "Drug Pregnancy Category"],
		["DrugPrescriptionStatus", "Drug Prescription Status"],
		["InfectiousAgentClass", "Infectious Agent Class"],
		["MedicalDevicePurpose", "Medical Device Purpose"],
		["MedicalEvidenceLevel", "Medical Evidence Level"],
		["MedicalImagingTechnique", "Medical Imaging Technique"],
		["MedicalObservationalStudyDesign", "Medical Observational Study Design"],
		["MedicalProcedureType", "Medical Procedure Type"],
		["MedicalStudyStatus", "Medical Study Status"],
		["MedicalTrialDesign", "Medical Trial Design"],
		["MedicineSystem", "Medicine System"],
		["PhysicalActivityCategory", "Physical Activity Category"],
		["PhysicalExam", "Physical Exam"],
		["MedicalProcedure", "Medical Procedure"],
		["DiagnosticProcedure", "Diagnostic Procedure"],
		["PalliativeProcedure", "Palliative Procedure"],
		["TherapeuticProcedure", "Therapeutic Procedure"],
		["MedicalRiskEstimator", "Medical Risk Estimator"],
		["MedicalRiskCalculator", "Medical Risk Calculator"],
		["MedicalRiskScore", "Medical Risk Score"],
		["MedicalRiskFactor", "Medical Risk Factor"],
		["MedicalSignOrSymptom", "Medical Sign or Symptom"],
		["MedicalSign", "Medical Sign"],
		["MedicalSymptom", "Medical Symptom"],
		["MedicalStudy", "Medical Study"],
		["MedicalObservationalStudy", "Medical Observational Study"],
		["MedicalTrial", "Medical Trial"],
		["MedicalTest", "Medical Test"],
		["BloodTest", "Blood Test"],
		["ImagingTest", "Imaging Test"],
		["MedicalTestPanel", "Medical Test Panel"],
		["PathologyTest", "Pathology Test"],
		["MedicalTherapy", "Medical Therapy"],
		["DietarySupplement", "Dietary Supplement"],
		["Drug", "Drug"],
		["DrugClass", "Drug Class"],
		["LifestyleModification", "Lifestyle Modification"],
		["PhysicalActivity", "Physical Activity"],
		["PhysicalTherapy", "Physical Therapy"],
		["PsychologicalTreatment", "Psychological Treatment"],
		["RadiationTherapy", "Radiation Therapy"],
		["SuperficialAnatomy", "Superficial Anatomy"],
		["Organization", "Organization"],
		["Corporation", "Corporation"],
		["EducationalOrganization", "Educational Organization"],
		["CollegeOrUniversity", "College or University"],
		["ElementarySchool", "Elementary School"],
		["HighSchool", "High School"],
		["MiddleSchool", "Middle School"],
		["Preschool", "Preschool"],
		["School", "School"],
		["GovernmentOrganization", "Government Organization"],
		["LocalBusiness", "Local Business"],
		["AnimalShelter", "Animal Shelter"],
		["AutomotiveBusiness", "Automotive Business"],
		["AutoBodyShop", "Auto Body Shop"],
		["AutoDealer", "Auto Dealer"],
		["AutoPartsStore", "Auto Parts Store"],
		["AutoRental", "Auto Rental"],
		["AutoRepair", "Auto Repair"],
		["AutoWash", "Auto Wash"],
		["GasStation", "Gas Station"],
		["MotorcycleDealer", "Motorcycle Dealer"],
		["MotorcycleRepair", "Motorcycle Repair"],
		["ChildCare", "Child Care"],
		["DryCleaningOrLaundry", "Dry Cleaning or Laundry"],
		["EmergencyService", "Emergency Service"],
		["FireStation", "Fire Station"],
		["Hospital", "Hospital"],
		["PoliceStation", "Police Station"],
		["EmploymentAgency", "Employment Agency"],
		["EntertainmentBusiness", "Entertainment Business"],
		["AdultEntertainment", "Adult Entertainment"],
		["AmusementPark", "Amusement Park"],
		["ArtGallery", "Art Gallery"],
		["Casino", "Casino"],
		["ComedyClub", "Comedy Club"],
		["MovieTheater", "Movie Theater"],
		["NightClub", "Night Club"],
		["FinancialService", "Financial Service"],
		["AccountingService", "Accounting Service"],
		["AutomatedTeller", "Automated Teller"],
		["BankOrCreditUnion", "Bank or Credit Union"],
		["InsuranceAgency", "Insurance Agency"],
		["FoodEstablishment", "Food Establishment"],
		["Bakery", "Bakery"],
		["BarOrPub", "Bar or Pub"],
		["Brewery", "Brewery"],
		["CafeOrCoffeeShop", "Cafe or Coffee Shop"],
		["FastFoodRestaurant", "Fast Food Restaurant"],
		["IceCreamShop", "Ice Cream Shop"],
		["Restaurant", "Restaurant"],
		["Winery", "Winery"],
		["GovernmentOffice", "Government Office"],
		["PostOffice", "Post Office"],
		["HealthAndBeautyBusiness", "Health And Beauty Business"],
		["BeautySalon", "Beauty Salon"],
		["DaySpa", "Day Spa"],
		["HairSalon", "Hair Salon"],
		["HealthClub", "Health Club"],
		["NailSalon", "Nail Salon"],
		["TattooParlor", "Tattoo Parlor"],
		["HomeAndConstructionBusiness", "Home And Construction Business"],
		["Electrician", "Electrician"],
		["GeneralContractor", "General Contractor"],
		["HVACBusiness", "HVAC Business"],
		["HousePainter", "House Painter"],
		["Locksmith", "Locksmith"],
		["MovingCompany", "Moving Company"],
		["Plumber", "Plumber"],
		["RoofingContractor", "Roofing Contractor"],
		["InternetCafe", "Internet Cafe"],
		["Library", "Library"],
		["LodgingBusiness", "Lodging Business"],
		["BedAndBreakfast", "Bed And Breakfast"],
		["Hostel", "Hostel"],
		["Hotel", "Hotel"],
		["Motel", "Motel"],
		["MedicalOrganization", "Medical Organization"],
		["Dentist", "Dentist"],
		["DiagnosticLab", "Diagnostic Lab"],
		["MedicalClinic", "Medical Clinic"],
		["Optician", "Optician"],
		["Pharmacy", "Pharmacy"],
		["Physician", "Physician"],
		["VeterinaryCare", "Veterinary Care"],
		["ProfessionalService", "Professional Service"],
		["Attorney", "Attorney"],
		["Notary", "Notary"],
		["RadioStation", "Radio Station"],
		["RealEstateAgent", "Real Estate Agent"],
		["RecyclingCenter", "Recycling Center"],
		["SelfStorage", "Self Storage"],
		["ShoppingCenter", "Shopping Center"],
		["SportsActivityLocation", "Sports Activity Location"],
		["BowlingAlley", "Bowling Alley"],
		["ExerciseGym", "Exercise Gym"],
		["GolfCourse", "Golf Course"],
		["PublicSwimmingPool", "Public Swimming Pool"],
		["SkiResort", "Ski Resort"],
		["SportsClub", "Sports Club"],
		["StadiumOrArena", "Stadium or Arena"],
		["TennisComplex", "Tennis Complex"],
		["Store", "Store"],
		["BikeStore", "Bike Store"],
		["BookStore", "Book Store"],
		["ClothingStore", "Clothing Store"],
		["ComputerStore", "Computer Store"],
		["ConvenienceStore", "Convenience Store"],
		["DepartmentStore", "Department Store"],
		["ElectronicsStore", "Electronics Store"],
		["Florist", "Florist"],
		["FurnitureStore", "Furniture Store"],
		["GardenStore", "Garden Store"],
		["GroceryStore", "Grocery Store"],
		["HardwareStore", "Hardware Store"],
		["HobbyShop", "Hobby Shop"],
		["HomeGoodsStore", "Home Goods Store"],
		["JewelryStore", "Jewelry Store"],
		["LiquorStore", "Liquor Store"],
		["MensClothingStore", "Mens Clothing Store"],
		["MobilePhoneStore", "Mobile Phone Store"],
		["MovieRentalStore", "Movie Rental Store"],
		["MusicStore", "Music Store"],
		["OfficeEquipmentStore", "Office Equipment Store"],
		["OutletStore", "Outlet Store"],
		["PawnShop", "Pawn Shop"],
		["PetStore", "Pet Store"],
		["ShoeStore", "Shoe Store"],
		["SportingGoodsStore", "Sporting Goods Store"],
		["TireShop", "Tire Shop"],
		["ToyStore", "Toy Store"],
		["WholesaleStore", "Wholesale Store"],
		["TelevisionStation", "Television Station"],
		["TouristInformationCenter", "Tourist Information Center"],
		["TravelAgency", "Travel Agency"],
		["NGO", "NGO"],
		["PerformingGroup", "Performing Group"],
		["DanceGroup", "Dance Group"],
		["MusicGroup", "Music Group"],
		["TheaterGroup", "Theater Group"],
		["SportsTeam", "Sports Team"],
		["Person", "Person"],
		["Place", "Place"],
		["AdministrativeArea", "Administrative Area"],
		["City", "City"],
		["Country", "Country"],
		["State", "State"],
		["CivicStructure", "Civic Structure"],
		["Airport", "Airport"],
		["Aquarium", "Aquarium"],
		["Beach", "Beach"],
		["BusStation", "Bus Station"],
		["BusStop", "Bus Stop"],
		["Campground", "Campground"],
		["Cemetery", "Cemetery"],
		["Crematorium", "Crematorium"],
		["EventVenue", "Event Venue"],
		["GovernmentBuilding", "Government Building"],
		["CityHall", "City Hall"],
		["Courthouse", "Courthouse"],
		["DefenceEstablishment", "Defence Establishment"],
		["Embassy", "Embassy"],
		["LegislativeBuilding", "Legislative Building"],
		["Museum", "Museum"],
		["MusicVenue", "Music Venue"],
		["Park", "Park"],
		["ParkingFacility", "Parking Facility"],
		["PerformingArtsTheater", "Performing Arts Theater"],
		["PlaceOfWorship", "Place of Worship"],
		["BuddhistTemple", "Buddhist Temple"],
		["CatholicChurch", "Catholic Church"],
		["Church", "Church"],
		["HinduTemple", "Hindu Temple"],
		["Mosque", "Mosque"],
		["Synagogue", "Synagogue"],
		["Playground", "Playground"],
		["RVPark", "RV Park"],
		["SubwayStation", "Subway Station"],
		["TaxiStand", "Taxi Stand"],
		["TrainStation", "Train Station"],
		["Zoo", "Zoo"],
		["Landform", "Landform"],
		["BodyOfWater", "Body of Water"],
		["Canal", "Canal"],
		["LakeBodyOfWater", "Lake Body of Water"],
		["OceanBodyOfWater", "Ocean Body of Water"],
		["Pond", "Pond"],
		["Reservoir", "Reservoir"],
		["RiverBodyOfWater", "River Body of Water"],
		["SeaBodyOfWater", "Sea Body of Water"],
		["Waterfall", "Waterfall"],
		["Continent", "Continent"],
		["Mountain", "Mountain"],
		["Volcano", "Volcano"],
		["LandmarksOrHistoricalBuildings", "Landmarks or Historical Buildings"],
		["AnimalShelter", "Animal Shelter"],
		["AutomotiveBusiness", "Automotive Business"],
		["AutoBodyShop", "Auto Body Shop"],
		["AutoDealer", "Auto Dealer"],
		["AutoRental", "Auto Rental"],
		["AutoRepair", "Auto Repair"],
		["AutoWash", "Auto Wash"],
		["GasStation", "Gas Station"],
		["MotorcycleDealer", "Motorcycle Dealer"],
		["MotorcycleRepair", "Motorcycle Repair"],
		["ChildCare", "Child Care"],
		["DryCleaningOrLaundry", "Dry Cleaning or Laundry"],
		["EmergencyService", "Emergency Service"],
		["EmploymentAgency", "Employment Agency"],
		["EntertainmentBusiness", "Entertainment Business"],
		["AdultEntertainment", "Adult Entertainment"],
		["AmusementPark", "Amusement Park"],
		["ArtGallery", "Art Gallery"],
		["Casino", "Casino"],
		["ComedyClub", "Comedy Club"],
		["NightClub", "Night Club"],
		["FinancialService", "Financial Service"],
		["AutomatedTeller", "Automated Teller"],
		["BankOrCreditUnion", "Bank or Credit Union"],
		["InsuranceAgency", "Insurance Agency"],
		["FoodEstablishment", "Food Establishment"],
		["Bakery", "Bakery"],
		["BarOrPub", "Bar or Pub"],
		["Brewery", "Brewery"],
		["CafeOrCoffeeShop", "Cafe or Coffee Shop"],
		["FastFoodRestaurant", "Fast Food Restaurant"],
		["IceCreamShop", "Ice Cream Shop"],
		["Restaurant", "Restaurant"],
		["Winery", "Winery"],
		["GovernmentOffice", "Government Office"],
		["PostOffice", "Post Office"],
		["HealthAndBeautyBusiness", "Health And Beauty Business"],
		["BeautySalon", "Beauty Salon"],
		["DaySpa", "Day Spa"],
		["HairSalon", "Hair Salon"],
		["NailSalon", "Nail Salon"],
		["TattooParlor", "Tattoo Parlor"],
		["HomeAndConstructionBusiness", "Home And Construction Business"],
		["HVACBusiness", "HVAC Business"],
		["MovingCompany", "Moving Company"],
		["InternetCafe", "Internet Cafe"],
		["Library", "Library"],
		["LodgingBusiness", "Lodging Business"],
		["BedAndBreakfast", "Bed And Breakfast"],
		["Hostel", "Hostel"],
		["Hotel", "Hotel"],
		["Motel", "Motel"],
		["MedicalOrganization", "Medical Organization"],
		["DiagnosticLab", "Diagnostic Lab"],
		["MedicalClinic", "Medical Clinic"],
		["Optician", "Optician"],
		["Pharmacy", "Pharmacy"],
		["Physician", "Physician"],
		["VeterinaryCare", "Veterinary Care"],
		["ProfessionalService", "Professional Service"],
		["Attorney", "Attorney"],
		["Notary", "Notary"],
		["RadioStation", "Radio Station"],
		["RealEstateAgent", "Real Estate Agent"],
		["RecyclingCenter", "Recycling Center"],
		["SelfStorage", "Self Storage"],
		["ShoppingCenter", "Shopping Center"],
		["SportsActivityLocation", "Sports Activity Location"],
		["BowlingAlley", "Bowling Alley"],
		["ExerciseGym", "Exercise Gym"],
		["GolfCourse", "Golf Course"],
		["PublicSwimmingPool", "Public Swimming Pool"],
		["SkiResort", "Ski Resort"],
		["SportsClub", "Sports Club"],
		["TennisComplex", "Tennis Complex"],
		["Store", "Store"],
		["BikeStore", "Bike Store"],
		["BookStore", "Book Store"],
		["ClothingStore", "Clothing Store"],
		["ComputerStore", "Computer Store"],
		["ConvenienceStore", "Convenience Store"],
		["DepartmentStore", "Department Store"],
		["ElectronicsStore", "Electronics Store"],
		["Florist", "Florist"],
		["FurnitureStore", "Furniture Store"],
		["GardenStore", "Garden Store"],
		["GroceryStore", "Grocery Store"],
		["HardwareStore", "Hardware Store"],
		["HobbyShop", "Hobby Shop"],
		["HomeGoodsStore", "Home Goods Store"],
		["JewelryStore", "Jewelry Store"],
		["LiquorStore", "Liquor Store"],
		["MensClothingStore", "Mens Clothing Store"],
		["MobilePhoneStore", "Mobile Phone Store"],
		["MovieRentalStore", "Movie Rental Store"],
		["MusicStore", "Music Store"],
		["OfficeEquipmentStore", "Office Equipment Store"],
		["OutletStore", "Outlet Store"],
		["PawnShop", "Pawn Shop"],
		["PetStore", "Pet Store"],
		["ShoeStore", "Shoe Store"],
		["SportingGoodsStore", "Sporting Goods Store"],
		["TireShop", "Tire Shop"],
		["ToyStore", "Toy Store"],
		["WholesaleStore", "Wholesale Store"],
		["TelevisionStation", "Television Station"],
		["TouristInformationCenter", "Tourist Information Center"],
		["TravelAgency", "Travel Agency"],
		["Residence", "Residence"],
		["ApartmentComplex", "Apartment Complex"],
		["GatedResidenceCommunity", "Gated Residence Community"],
		["SingleFamilyResidence", "Single Family Residence"],
		["TouristAttraction", "Tourist Attraction"],
		["Product", "Product"],
		["about", "About"],
		["acceptsReservations", "Accepts Reservations"],
		["accountablePerson", "Accountable Person"],
		["action", "Action"],
		["activeIngredient", "Active Ingredient"],
		["activityDuration", "Activity Duration"],
		["activityFrequency", "Activity Frequency"],
		["actor", "Actor"],
		["actors", "Actors"],
		["additionalName", "Additional Name"],
		["additionalType", "Additional Type"],
		["additionalVariable", "Additional Variable"],
		["address", "Address"],
		["addressCountry", "Address Country"],
		["addressLocality", "Address Locality"],
		["addressRegion", "Address Region"],
		["administrationRoute", "Administration Route"],
		["adverseOutcome", "Adverse Outcome"],
		["affectedBy", "Affected by"],
		["affiliation", "Affiliation"],
		["aggregateRating", "Aggregate Rating"],
		["album", "Album"],
		["albums", "Albums"],
		["alcoholWarning", "Alcohol Warning"],
		["algorithm", "Algorithm"],
		["alternateName", "Alternate Name"],
		["alternativeHeadline", "Alternative Headline"],
		["alumni", "Alumni"],
		["alumniOf", "Alumni of"],
		["antagonist", "Antagonist"],
		["applicableLocation", "Applicable Location"],
		["applicationCategory", "Application Category"],
		["applicationSubCategory", "Application Sub Category"],
		["applicationSuite", "Application Suite"],
		["arterialBranch", "Arterial Branch"],
		["articleBody", "Article Body"],
		["articleSection", "Article Section"],
		["aspect", "Aspect"],
		["associatedAnatomy", "Associated Anatomy"],
		["associatedArticle", "Associated Article"],
		["associatedMedia", "Associated Media"],
		["associatedPathophysiology", "Associated Pathophysiology"],
		["attendee", "Attendee"],
		["attendees", "Attendees"],
		["audience", "Audience"],
		["audio", "Audio"],
		["author", "Author"],
		["availability", "Availability"],
		["availableIn", "Available in"],
		["availableService", "Available Service"],
		["availableStrength", "Available Strength"],
		["availableTest", "Available Test"],
		["award", "Award"],
		["awards", "Awards"],
		["background", "Background"],
		["baseSalary", "Base Salary"],
		["benefits", "Benefits"],
		["bestRating", "Best Rating"],
		["biomechnicalClass", "Biomechnical Class"],
		["birthDate", "Birth Date"],
		["bitrate", "Bitrate"],
		["blogPost", "Blog Post"],
		["blogPosts", "Blog Posts"],
		["bloodSupply", "Blood Supply"],
		["bodyLocation", "Body Location"],
		["bookEdition", "Book Edition"],
		["bookFormat", "Book Format"],
		["box", "Box"],
		["branch", "Branch"],
		["branchOf", "Branch of"],
		["brand", "Brand"],
		["breadcrumb", "Breadcrumb"],
		["breastfeedingWarning", "Breastfeeding Warning"],
		["browserRequirements", "Browser Requirements"],
		["byArtist", "By Artist"],
		["calories", "Calories"],
		["caption", "Caption"],
		["carbohydrateContent", "Carbohydrate Content"],
		["carrierRequirements", "Carrier Requirements"],
		["category", "Category"],
		["cause", "Cause"],
		["causeOf", "Cause of"],
		["children", "Children"],
		["cholesterolContent", "Cholesterol Content"],
		["circle", "Circle"],
		["citation", "Citation"],
		["clincalPharmacology", "Clincal Pharmacology"],
		["code", "Code"],
		["codeValue", "Code Value"],
		["codingSystem", "Coding System"],
		["colleague", "Colleague"],
		["colleagues", "Colleagues"],
		["comment", "Comment"],
		["commentText", "Comment Text"],
		["commentTime", "Comment Time"],
		["comprisedOf", "Comprised of"],
		["connectedTo", "Connected to"],
		["contactPoint", "Contact Point"],
		["contactPoints", "Contact Points"],
		["contactType", "Contact Type"],
		["containedIn", "Contained in"],
		["contentLocation", "Content Location"],
		["contentRating", "Content Rating"],
		["contentSize", "Content Size"],
		["contentUrl", "Content Url"],
		["contraindication", "Contraindication"],
		["contributor", "Contributor"],
		["cookTime", "Cook Time"],
		["cookingMethod", "Cooking Method"],
		["copyrightHolder", "Copyright Holder"],
		["copyrightYear", "Copyright Year"],
		["cost", "Cost"],
		["costCategory", "Cost Category"],
		["costCurrency", "Cost Currency"],
		["costOrigin", "Cost Origin"],
		["costPerUnit", "Cost Per Unit"],
		["countriesNotSupported", "Countries Not Supported"],
		["countriesSupported", "Countries Supported"],
		["creator", "Creator"],
		["currenciesAccepted", "Currencies Accepted"],
		["dateCreated", "Date Created"],
		["dateModified", "Date Modified"],
		["datePosted", "Date Posted"],
		["datePublished", "Date Published"],
		["dateline", "Dateline"],
		["deathDate", "Death Date"],
		["description", "Description"],
		["device", "Device"],
		["diagnosis", "Diagnosis"],
		["diagram", "Diagram"],
		["dietFeatures", "Diet Features"],
		["differentialDiagnosis", "Differential Diagnosis"],
		["director", "Director"],
		["discusses", "Discusses"],
		["discussionUrl", "Discussion Url"],
		["distinguishingSign", "Distinguishing Sign"],
		["dosageForm", "Dosage Form"],
		["doseSchedule", "Dose Schedule"],
		["doseUnit", "Dose Unit"],
		["doseValue", "Dose Value"],
		["downloadUrl", "Download Url"],
		["drainsTo", "Drains to"],
		["drug", "Drug"],
		["drugClass", "Drug Class"],
		["drugUnit", "Drug Unit"],
		["duplicateTherapy", "Duplicate Therapy"],
		["duration", "Duration"],
		["editor", "Editor"],
		["educationRequirements", "Education Requirements"],
		["elevation", "Elevation"],
		["email", "Email"],
		["embedUrl", "Embed Url"],
		["employee", "Employee"],
		["employees", "Employees"],
		["employmentType", "Employment Type"],
		["encodesCreativeWork", "Encodes Creative Work"],
		["encoding", "Encoding"],
		["encodingFormat", "Encoding Format"],
		["encodings", "Encodings"],
		["endDate", "End Date"],
		["endorsers", "Endorsers"],
		["epidemiology", "Epidemiology"],
		["episode", "Episode"],
		["episodeNumber", "Episode Number"],
		["episodes", "Episodes"],
		["estimatesRiskOf", "Estimates Risk of"],
		["event", "Event"],
		["events", "Events"],
		["evidenceLevel", "Evidence Level"],
		["evidenceOrigin", "Evidence Origin"],
		["exerciseType", "Exercise Type"],
		["exifData", "Exif Data"],
		["expectedPrognosis", "Expected Prognosis"],
		["experienceRequirements", "Experience Requirements"],
		["expertConsiderations", "Expert Considerations"],
		["expires", "Expires"],
		["familyName", "Family Name"],
		["fatContent", "Fat Content"],
		["faxNumber", "Fax Number"],
		["featureList", "Feature List"],
		["fiberContent", "Fiber Content"],
		["fileFormat", "File Format"],
		["fileSize", "File Size"],
		["follows", "Follows"],
		["followup", "Followup"],
		["foodWarning", "Food Warning"],
		["founder", "Founder"],
		["founders", "Founders"],
		["foundingDate", "Founding Date"],
		["frequency", "Frequency"],
		["function", "Function"],
		["functionalClass", "Functional Class"],
		["gender", "Gender"],
		["genre", "Genre"],
		["geo", "Geo"],
		["givenName", "Given Name"],
		["guideline", "Guideline"],
		["guidelineDate", "Guideline Date"],
		["guidelineSubject", "Guideline Subject"],
		["headline", "Headline"],
		["height", "Height"],
		["highPrice", "High Price"],
		["hiringOrganization", "Hiring Organization"],
		["homeLocation", "Home Location"],
		["honorificPrefix", "Honorific Prefix"],
		["honorificSuffix", "Honorific Suffix"],
		["hospitalAffiliation", "Hospital Affiliation"],
		["howPerformed", "How Performed"],
		["identifyingExam", "Identifying Exam"],
		["identifyingTest", "Identifying Test"],
		["illustrator", "Illustrator"],
		["image", "Image"],
		["imagingTechnique", "Imaging Technique"],
		["inAlbum", "In Album"],
		["inLanguage", "In Language"],
		["inPlaylist", "In Playlist"],
		["incentives", "Incentives"],
		["includedRiskFactor", "Included Risk Factor"],
		["increasesRiskOf", "Increases Risk of"],
		["indication", "Indication"],
		["industry", "Industry"],
		["infectiousAgent", "Infectious Agent"],
		["infectiousAgentClass", "Infectious Agent Class"],
		["ingredients", "Ingredients"],
		["insertion", "Insertion"],
		["installUrl", "Install Url"],
		["intensity", "Intensity"],
		["interactingDrug", "Interacting Drug"],
		["interactionCount", "Interaction Count"],
		["isAvailableGenerically", "Is Available Generically"],
		["isFamilyFriendly", "Is Family Friendly"],
		["isPartOf", "Is Part of"],
		["isProprietary", "Is Proprietary"],
		["isbn", "ISBN"],
		["itemCondition", "Item Condition"],
		["itemListElement", "Item List Element"],
		["itemListOrder", "Item List Order"],
		["itemOffered", "Item Offered"],
		["itemReviewed", "Item Reviewed"],
		["jobLocation", "Job Location"],
		["jobTitle", "Job Title"],
		["keywords", "Keywords"],
		["knows", "Knows"],
		["labelDetails", "Label Details"],
		["lastReviewed", "Last Reviewed"],
		["latitude", "Latitude"],
		["legalStatus", "Legal Status"],
		["line", "Line"],
		["location", "Location"],
		["longitude", "Longitude"],
		["lowPrice", "Low Price"],
		["mainContentOfPage", "Main Content of Page"],
		["manufacturer", "Manufacturer"],
		["map", "Map"],
		["maps", "Maps"],
		["maximumIntake", "Maximum Intake"],
		["mechanismOfAction", "Mechanism of Action"],
		["medicalSpecialty", "Medical Specialty"],
		["medicineSystem", "Medicine System"],
		["member", "Member"],
		["memberOf", "Member of"],
		["members", "Members"],
		["memoryRequirements", "Memory Requirements"],
		["mentions", "Mentions"],
		["menu", "Menu"],
		["model", "Model"],
		["musicBy", "Music by"],
		["musicGroupMember", "Music Group Member"],
		["name", "Name"],
		["nationality", "Nationality"],
		["naturalProgression", "Natural Progression"],
		["nerve", "Nerve"],
		["nerveMotor", "Nerve Motor"],
		["nonProprietaryName", "Non Proprietary Name"],
		["normalRange", "Normal Range"],
		["numTracks", "Num Tracks"],
		["numberOfEpisodes", "Number of Episodes"],
		["numberOfPages", "Number of Pages"],
		["nutrition", "Nutrition"],
		["occupationalCategory", "Occupational Category"],
		["offerCount", "Offer Count"],
		["offers", "Offers"],
		["openingHours", "Opening Hours"],
		["operatingSystem", "Operating System"],
		["origin", "Origin"],
		["originatesFrom", "Originates From"],
		["outcome", "Outcome"],
		["overdosage", "Overdosage"],
		["overview", "Overview"],
		["parent", "Parent"],
		["parents", "Parents"],
		["partOfSeason", "Part of Season"],
		["partOfSystem", "Part of System"],
		["partOfTVSeries", "Part of TV Series"],
		["pathophysiology", "Pathophysiology"],
		["paymentAccepted", "Payment Accepted"],
		["performer", "Performer"],
		["performerIn", "Performer in"],
		["performers", "Performers"],
		["permissions", "Permissions"],
		["phase", "Phase"],
		["photo", "Photo"],
		["photos", "Photos"],
		["physiologicalBenefits", "Physiological Benefits"],
		["playerType", "Player Type"],
		["polygon", "Polygon"],
		["population", "Population"],
		["possibleComplication", "Possible Complication"],
		["possibleTreatment", "Possible Treatment"],
		["postOfficeBoxNumber", "Post Office Box Number"],
		["postOp", "Post Op"],
		["postalCode", "Postal Code"],
		["preOp", "Pre Op"],
		["pregnancyCategory", "Pregnancy Category"],
		["pregnancyWarning", "Pregnancy Warning"],
		["prepTime", "Prep Time"],
		["preparation", "Preparation"],
		["prescribingInfo", "Prescribing Info"],
		["prescriptionStatus", "Prescription Status"],
		["price", "Price"],
		["priceCurrency", "Price Currency"],
		["priceRange", "Price Range"],
		["priceValidUntil", "Price Valid Until"],
		["primaryImageOfPage", "Primary Image of Page"],
		["primaryPrevention", "Primary Prevention"],
		["printColumn", "Print Column"],
		["printEdition", "Print Edition"],
		["printPage", "Print Page"],
		["printSection", "Print Section"],
		["procedure", "Procedure"],
		["procedureType", "Procedure Type"],
		["processorRequirements", "Processor Requirements"],
		["producer", "Producer"],
		["productID", "Product ID"],
		["productionCompany", "Production Company"],
		["proprietaryName", "Proprietary Name"],
		["proteinContent", "Protein Content"],
		["provider", "Provider"],
		["publicationType", "Publication Type"],
		["publisher", "Publisher"],
		["publishingPrinciples", "Publishing Principles"],
		["purpose", "Purpose"],
		["qualifications", "Qualifications"],
		["ratingCount", "Rating Count"],
		["ratingValue", "Rating Value"],
		["recipeCategory", "Recipe Category"],
		["recipeCuisine", "Recipe Cuisine"],
		["recipeInstructions", "Recipe Instructions"],
		["recipeYield", "Recipe Yield"],
		["recognizingAuthority", "Recognizing Authority"],
		["recommendationStrength", "Recommendation Strength"],
		["recommendedIntake", "Recommended Intake"],
		["regionDrained", "Region Drained"],
		["regionsAllowed", "Regions Allowed"],
		["relatedAnatomy", "Related Anatomy"],
		["relatedCondition", "Related Condition"],
		["relatedDrug", "Related Drug"],
		["relatedLink", "Related Link"],
		["relatedStructure", "Related Structure"],
		["relatedTherapy", "Related Therapy"],
		["relatedTo", "Related to"],
		["releaseNotes", "Release Notes"],
		["relevantSpecialty", "Relevant Specialty"],
		["repetitions", "Repetitions"],
		["replyToUrl", "Reply to Url"],
		["representativeOfPage", "Representative of Page"],
		["requirements", "Requirements"],
		["requiresSubscription", "Requires Subscription"],
		["responsibilities", "Responsibilities"],
		["restPeriods", "Rest Periods"],
		["review", "Review"],
		["reviewBody", "Review Body"],
		["reviewCount", "Review Count"],
		["reviewRating", "Review Rating"],
		["reviewedBy", "Reviewed by"],
		["reviews", "Reviews"],
		["riskFactor", "Risk Factor"],
		["risks", "Risks"],
		["runsTo", "Runs to"],
		["safetyConsideration", "Safety Consideration"],
		["salaryCurrency", "Salary Currency"],
		["saturatedFatContent", "Saturated Fat Content"],
		["screenshot", "Screenshot"],
		["season", "Season"],
		["seasonNumber", "Season Number"],
		["seasons", "Seasons"],
		["secondaryPrevention", "Secondary Prevention"],
		["seller", "Seller"],
		["sensoryUnit", "Sensory Unit"],
		["seriousAdverseOutcome", "Serious Adverse Outcome"],
		["servesCuisine", "Serves Cuisine"],
		["servingSize", "Serving Size"],
		["sibling", "Sibling"],
		["siblings", "Siblings"],
		["signDetected", "Sign Detected"],
		["signOrSymptom", "Sign or Symptom"],
		["significance", "Significance"],
		["significantLink", "Significant Link"],
		["significantLinks", "Significant Links"],
		["skills", "Skills"],
		["sodiumContent", "Sodium Content"],
		["softwareVersion", "Software Version"],
		["source", "Source"],
		["sourceOrganization", "Source Organization"],
		["sourcedFrom", "Sourced From"],
		["specialCommitments", "Special Commitments"],
		["specialty", "Specialty"],
		["sponsor", "Sponsor"],
		["spouse", "Spouse"],
		["stage", "Stage"],
		["stageAsNumber", "Stage As Number"],
		["startDate", "Start Date"],
		["status", "Status"],
		["storageRequirements", "Storage Requirements"],
		["streetAddress", "Street Address"],
		["strengthUnit", "Strength Unit"],
		["strengthValue", "Strength Value"],
		["structuralClass", "Structural Class"],
		["study", "Study"],
		["studyDesign", "Study Design"],
		["studyLocation", "Study Location"],
		["studySubject", "Study Subject"],
		["subEvent", "Sub Event"],
		["subEvents", "Sub Events"],
		["subStageSuffix", "Sub Stage Suffix"],
		["subStructure", "Sub Structure"],
		["subTest", "Sub Test"],
		["subtype", "Subtype"],
		["sugarContent", "Sugar Content"],
		["superEvent", "Super Event"],
		["supplyTo", "Supply to"],
		["targetPopulation", "Target Population"],
		["telephone", "Telephone"],
		["text", "Text"],
		["thumbnail", "Thumbnail"],
		["thumbnailUrl", "Thumbnail Url"],
		["tickerSymbol", "Ticker Symbol"],
		["tissueSample", "Tissue Sample"],
		["title", "Title"],
		["totalTime", "Total Time"],
		["track", "Track"],
		["tracks", "Tracks"],
		["trailer", "Trailer"],
		["transFatContent", "Trans Fat Content"],
		["transcript", "Transcript"],
		["transmissionMethod", "Transmission Method"],
		["trialDesign", "Trial Design"],
		["tributary", "Tributary"],
		["typicalTest", "Typical Test"],
		["unsaturatedFatContent", "Unsaturated Fat Content"],
		["uploadDate", "Upload Date"],
		["url", "URL"],
		["usedToDiagnose", "Used to Diagnose"],
		["usesDevice", "Uses Device"],
		["version", "Version"],
		["video", "Video"],
		["videoFrameSize", "Video Frame Size"],
		["videoQuality", "Video Quality"],
		["warning", "Warning"],
		["width", "Width"],
		["wordCount", "Word Count"],
		["workHours", "Work Hours"],
		["workLocation", "Work Location"],
		["workload", "Workload"],
		["worksFor", "Works for"],
		["worstRating", "Worst Rating"],
	];